### ISSUE TITLE
Why I can't upload the pdf file

### ISSUE THREAD

**Issue by spy14414** [kuroko1t/pyuploader#1]
Can I use your code for my job？QAQ

**Comment by kuroko1t** [comment]
sure, ok. this project is MIT LICENCE.

**Comment by spy14414** [comment]
Hello,I used your code to upload a pdf file,which is 5.53MB. But it failed,and data transfer was incomplete. Do you have any advice for me?

**Comment by kuroko1t** [comment]
Hello,i will try uploading pdf(~5MB) ．what's your  python version?

**Comment by kuroko1t** [comment]
i tried(pdf size 6.3MB), went well file transfer. 

this is my environment.
OS: ubuntu 16.04
python  3.6.5
pip module  :  listed in requirement.txt 

port 50053 used for transfer is fixed in [my code](https://github.com/kuroko1t/pyuploader/blob/fd4d7e26e4a23bb08096a7e3ba7d94e375b40b47/uploader.py#L18) , is it available ?

**Comment by spy14414** [comment]
Sorry for my late reply. You are right.There is no problem to transfer pdf file.
ps:Are there cherry blossoms near where you live? qaq

**Comment by kuroko1t** [comment]
yeah.cherry blossoms is near.
